### ISSUE TITLE
It's C

### ISSUE THREAD

**Issue by Mimikkk** [ProgramistycznySwir/SO-Proyekt1#1]
Shouldn't be C

**Comment by ProgramistycznySwir** [comment]
I've run search and it clearly say there is no C (pic included)
![NoC](https://user-images.githubusercontent.com/39069042/116787616-46422d80-aaa5-11eb-9f67-561fe81f5d8b.PNG)

**Comment by ProgramistycznySwir** [comment]
I swear it's those useless ticket like this, they make me ANGRYYY

CLOSED
